import { ClipboardList, Printer, X } from 'lucide-react'
import { formatCurrency, getEffectivePrice } from '../lib/format'
import type { CartItem, OrderTotals } from '../types'
import { AppLogo } from './AppLogo'

interface AdisyonModalProps { cart: CartItem[]; customerName?: string; discountRate: number; isOpen: boolean; note: string; onClose: () => void; orderNumber: string; totals: OrderTotals }

export function AdisyonModal({ cart, customerName, discountRate, isOpen, note, onClose, orderNumber, totals }: AdisyonModalProps) {
  if (!isOpen) return null
  const now = new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date())
  return <div className="overlay" role="dialog" aria-modal="true" aria-label="Adisyon"><div className="modal adisyon-modal"><div className="modal-head"><div><p className="section-kicker flex items-center gap-1"><ClipboardList size={13} /> Masa adisyonu</p><h2 className="section-title">Adisyon · #{orderNumber}</h2></div><button type="button" className="close-button" onClick={onClose} aria-label="Adisyonu kapat"><X size={18} /></button></div><div className="adisyon-sheet"><div className="adisyon-top flex items-center justify-between"><div className="flex items-center gap-2.5"><AppLogo className="w-9 h-9 object-contain" /><div><strong>ECO COFFEE</strong><span>Gaziantep · Nurdağı</span></div></div><div className="adisyon-status">AÇIK<br /><small>{now}</small></div></div><div className="adisyon-info"><span>{orderNumber}</span>{customerName && <span>Müşteri: {customerName}</span>}<span>Garson: ECO</span><span>#{orderNumber}</span></div><div className="adisyon-columns"><span>Ürün</span><span>Adet</span><span>Tutar</span></div>{cart.length === 0 ? <div className="adisyon-empty">Adisyon için sepete ürün ekleyin.</div> : cart.map((item) => <div className="adisyon-item" key={item.cartItemId} style={{ display: 'grid', gridTemplateColumns: '1fr 45px 74px', gap: '9px', padding: '10px 0', borderBottom: '1px solid #f0e8e0' }}><span><strong style={{display: 'block', color: '#5c493d', fontSize: '13px'}}>{item.name}</strong><small style={{color: '#a68a78', fontSize: '10px'}}>{formatCurrency(getEffectivePrice(item))} / adet</small></span><b style={{color: '#5c493d', fontSize: '12px'}}>{item.quantity}</b><b style={{color: '#5c493d', fontSize: '12px', textAlign: 'right'}}>{formatCurrency(getEffectivePrice(item) * item.quantity)}</b>{item.selectedOptions && item.selectedOptions.length > 0 && <div className="adisyon-item-options">{item.selectedOptions.map(o => o.priceDelta !== 0 ? `${o.optionName} (${o.priceDelta > 0 ? '+' : ''}${o.priceDelta}₺)` : o.optionName).join(', ')}</div>}</div>)}<div className="adisyon-divider" /><div className="adisyon-total"><span>Ara toplam</span><b>{formatCurrency(totals.subtotal)}</b></div>{discountRate > 0 && <div className="adisyon-total discount"><span>İndirim</span><b>-{formatCurrency(totals.discount)}</b></div>}<div className="adisyon-grand"><span>TOPLAM</span><strong>{formatCurrency(totals.total)}</strong></div>{note && <div className="adisyon-note"><b>Sipariş notu</b><span>{note}</span></div>}<div className="adisyon-footer">Ödeme bekleniyor</div></div><div className="receipt-actions"><button type="button" className="outline-action flex-1" onClick={onClose}>Kapat</button><button type="button" className="solid-action flex-1" onClick={() => { window.print() }}><Printer size={15} className="mr-2 inline" />Adisyonu Yazdır</button></div></div></div>
}
